# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/
$(document).ready ->
  token = $('meta[name="csrf-token"]').attr('content')
  $('#text').keyup (e) ->
    $.ajax
      data:
        'text': $('textarea[name=\'text\']').val()
        'displacement': $('input[name=\'displacement\']').val()
        'groups': $('input[name=\'groups\']').val()
      url: '/cifrado'
      type: 'post'
      dataType: 'json'
      headers: 'X-CSRF-Token': token
      success: (response) ->
        #una vez que el archivo recibe el request lo procesa y lo devuelve
        console.log response
        $("#encryption-text").html(response.encryption);
        $("#invert-text").html(response.invert);
        #$("#groups-text").html(response[2]);
        return
    e.preventDefault()
    return
  $('#displacement').click (e) ->
    $.ajax
      data:
        'text': $('textarea[name=\'text\']').val()
        'displacement': $('input[name=\'displacement\']').val()
        'groups': $('input[name=\'groups\']').val()
      url: '/generator'
      type: 'post'
      dataType: 'json'
      success: (response) ->
        #una vez que el archivo recibe el request lo procesa y lo devuelve
        console.log response[0]
        $("#encryption-text").html(response.encryption);
        $("#invert-text").html(response.invert);
        $('#groups-text').html response[2]
        return
    e.preventDefault()
    return
  $('#displacement').keyup (e) ->
    $.ajax
      data:
        'text': $('textarea[name=\'text\']').val()
        'displacement': $('input[name=\'displacement\']').val()
        'groups': $('input[name=\'groups\']').val()
      url: '/generator'
      type: 'post'
      dataType: 'json'
      success: (response) ->
        #una vez que el archivo recibe el request lo procesa y lo devuelve
        console.log response[0]
        $("#encryption-text").html(response.encryption);
        $("#invert-text").html(response.invert);
        $('#groups-text').html response[2]
        return
    e.preventDefault()
    return
  $('#groups').click (e) ->
    $.ajax
      data:
        'text': $('textarea[name=\'text\']').val()
        'displacement': $('input[name=\'displacement\']').val()
        'groups': $('input[name=\'groups\']').val()
      url: '/generator'
      type: 'post'
      dataType: 'json'
      success: (response) ->
        #una vez que el archivo recibe el request lo procesa y lo devuelve
        console.log response[0]
        $("#encryption-text").html(response.encryption);
        $("#invert-text").html(response.invert);
        $('#groups-text').html response[2]
        return
    e.preventDefault()
    return
  $('#groups').keyup (e) ->
    $.ajax
      data:
        'text': $('textarea[name=\'text\']').val()
        'displacement': $('input[name=\'displacement\']').val()
        'groups': $('input[name=\'groups\']').val()
      url: '/generator'
      type: 'post'
      dataType: 'json'
      success: (response) ->
        #una vez que el archivo recibe el request lo procesa y lo devuelve
        console.log response[0]
        $("#encryption-text").html(response.encryption);
        $("#invert-text").html(response.invert);
        $('#groups-text').html response[2]
        return
    e.preventDefault()
    return
  return

# ---
# generated by js2coffee 2.2.0
